# Generated by Django 5.2.3 on 2025-08-25 08:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CallCommissionComponent",
            new_name="CallCommissionMember",
        ),
    ]
