# Generated by Django 5.2.3 on 2025-08-26 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_alter_application_declaration_of_value_and_more"),
        ("management", "0003_applicationinsertionrequiredcommissionreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationinsertionrequiredcommissionreview",
            name="insertion",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review",
                to="applications.applicationinsertionrequired",
            ),
        ),
    ]
