# Generated by Django 5.2.3 on 2025-08-28 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0004_call_insertions_only_from_same_course"),
        ("management", "0006_callcommission_show_results"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callcommission",
            name="call",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commission",
                to="calls.call",
            ),
        ),
    ]
