# Generated by Django 5.2.3 on 2025-08-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0009_applicationinsertioncommissionreviewlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationinsertioncommissionreviewlog",
            options={"ordering": ("-created",)},
        ),
    ]
