# Generated by Django 5.2.3 on 2025-08-28 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("management", "0010_alter_applicationinsertioncommissionreviewlog_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="applicationinsertioncommissionreviewlog",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="management__content_9cce15_idx",
            ),
        ),
    ]
