# Generated by Django 5.2.5 on 2025-09-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0011_applicationinsertioncommissionreviewlog_management__content_9cce15_idx",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApplicationInsertionCommissionReviewLog",
        ),
    ]
