# Generated by Django 5.2.5 on 2025-09-11 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0012_delete_applicationinsertioncommissionreviewlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationinsertionfreecommissionreview",
            name="changed_credits",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="applicationinsertionrequiredcommissionreview",
            name="changed_credits",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
