# Generated by Django 5.2.5 on 2025-09-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0013_alter_applicationinsertionfreecommissionreview_changed_credits_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationinsertionfreecommissionreview",
            name="changed_grade",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="applicationinsertionrequiredcommissionreview",
            name="changed_grade",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
