# Generated by Django 5.2.5 on 2025-09-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0014_applicationinsertionfreecommissionreview_changed_grade_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationinsertionfreecommissionreview",
            name="changed_grade",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="applicationinsertionrequiredcommissionreview",
            name="changed_grade",
            field=models.CharField(max_length=255),
        ),
    ]
