# Generated by Django 5.2.5 on 2025-09-11 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0015_alter_applicationinsertionfreecommissionreview_changed_grade_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationinsertionfreecommissionreview",
            name="changed_credits",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="applicationinsertionrequiredcommissionreview",
            name="changed_credits",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
