# Generated by Django 5.2.3 on 2025-07-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_applicationinsertionfree_source_university_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="protocol_taken",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
