# Generated by Django 5.2.3 on 2025-07-17 12:31

import applications.models
import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_application_protocol_taken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="declaration_of_value",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=applications.models._attachment_path_application,
                validators=[
                    applications.validators.validate_attachment_extension,
                    applications.validators.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="home_exams_certification",
            field=models.FileField(
                max_length=255,
                upload_to=applications.models._attachment_path_application,
                validators=[
                    applications.validators.validate_attachment_extension,
                    applications.validators.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="home_language_certification",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=applications.models._attachment_path_application,
                validators=[
                    applications.validators.validate_attachment_extension,
                    applications.validators.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="home_teaching_plan",
            field=models.FileField(
                max_length=255,
                upload_to=applications.models._attachment_path_application,
                validators=[
                    applications.validators.validate_attachment_extension,
                    applications.validators.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="home_votes_conversion",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=applications.models._attachment_path_application,
                validators=[
                    applications.validators.validate_attachment_extension,
                    applications.validators.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="payment_receipt",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=applications.models._attachment_path_application,
                validators=[
                    applications.validators.validate_attachment_extension,
                    applications.validators.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="applicationinsertionrequired",
            name="source_teaching_attachment",
            field=models.FileField(
                max_length=255,
                upload_to=applications.models._attachment_path_required,
                validators=[
                    applications.validators.validate_attachment_extension,
                    applications.validators.validate_file_size,
                ],
            ),
        ),
    ]
