# Generated by Django 5.2.5 on 2025-09-16 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_alter_application_declaration_of_value_and_more"),
        ("calls", "0004_call_insertions_only_from_same_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="calls.call",
            ),
        ),
    ]
