# Generated by Django 5.2.5 on 2026-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_alter_application_call"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationinsertionrequired",
            name="target_teaching_ssd",
            field=models.CharField(max_length=255),
        ),
    ]
