# Generated by Django 5.2.5 on 2026-08-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_alter_applicationinsertionrequired_target_teaching_ssd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationinsertionfree",
            name="source_teaching_ssd",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="applicationinsertionrequired",
            name="source_teaching_ssd",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
