# Generated by Django 5.2.5 on 2026-08-18 07:33

import applications.models
import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0007_alter_applicationinsertionfree_source_teaching_ssd_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationinsertionfree",
            name="source_teaching_attachment",
            field=models.FileField(
                max_length=255,
                upload_to=applications.models._attachment_path_free,
                validators=[
                    applications.validators.validate_attachment_extension,
                    applications.validators.validate_file_size,
                ],
            ),
        ),
    ]
