# Generated by Django 5.2.3 on 2025-07-11 10:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titulus_ws', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title_it', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('course_cod', models.CharField(max_length=10)),
                ('course_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2200)])),
                ('course_year', models.PositiveIntegerField(default=1)),
                ('places_available', models.PositiveIntegerField(default=1)),
                ('credits_threshold', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('credits_reference_year', models.PositiveIntegerField()),
                ('study_plan_cod', models.CharField(max_length=10)),
                ('payment_required', models.BooleanField(default=False)),
                ('payment_url', models.URLField(blank=True, default='')),
                ('protocol_required', models.BooleanField(default=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('notes_it', models.TextField(blank=True, default='')),
                ('notes_en', models.TextField(blank=True, default='')),
                ('course_json_it', models.JSONField(blank=True, null=True)),
                ('course_json_en', models.JSONField(blank=True, null=True)),
                ('course_studyplans_json_it', models.JSONField(blank=True, null=True)),
                ('course_studyplans_json_en', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title_it', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('content_it', models.TextField()),
                ('content_en', models.TextField()),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.call')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallTitulusConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('uo', models.CharField(choices=[('', '-')], max_length=12, verbose_name='UO')),
                ('uo_rpa', models.CharField(blank=True, default='', help_text='Nominativo RPA', max_length=255, verbose_name='RPA')),
                ('uo_rpa_username', models.CharField(blank=True, default='', help_text='Username RPA sul sistema di protocollo', max_length=255, verbose_name='RPA username')),
                ('uo_rpa_matricola', models.CharField(blank=True, default='', help_text='Matricola RPA sul sistema di protocollo', max_length=255, verbose_name='RPA matricola')),
                ('send_email', models.BooleanField(default=True, verbose_name='Invia e-mail a RPA')),
                ('email', models.EmailField(blank=True, help_text='default: default@example.pec.it', max_length=255, null=True, verbose_name='E-mail')),
                ('cod_titolario', models.CharField(choices=[('', '-')], max_length=12, verbose_name='Codice titolario')),
                ('fascicolo_numero', models.CharField(blank=True, default='', max_length=255, verbose_name='Fascicolo numero')),
                ('fascicolo_anno', models.IntegerField(blank=True, null=True, verbose_name='Fascicolo anno')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.call')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='titulus_ws.titulusconfiguration')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configurazione WS Protocollo Categoria',
                'verbose_name_plural': 'Configurazioni WS Protocollo Categorie',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CallExcludedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.call')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('call', 'code'), name='unique_call_excluded_activity_code')],
            },
        ),
        migrations.CreateModel(
            name='CallFreeCreditsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('course_year', models.PositiveIntegerField(default=1)),
                ('min_value', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_value', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.call')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('call', 'course_year'), name='unique_call_free_credits_rule')],
            },
        ),
    ]
