# Generated by Django 5.2.3 on 2025-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ('ordering',)},
        ),
        migrations.AddField(
            model_name='call',
            name='ordering',
            field=models.IntegerField(default=10),
        ),
    ]
