# Generated by Django 5.2.3 on 2025-07-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_alter_call_options_call_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
