# Generated by Django 5.2.3 on 2025-07-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0003_call_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="insertions_only_from_same_course",
            field=models.BooleanField(default=False),
        ),
    ]
