# Generated by Django 5.2.5 on 2026-09-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0004_call_insertions_only_from_same_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
