# Generated by Django 5.2.5 on 2026-09-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0006_callparticipant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="call",
            old_name="public",
            new_name="is_public",
        ),
    ]
